const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "+94710701946"
const SESSION_ID = "PRABATH-MD~nc0yFRBA#VBXCiqy8HxaQvwwg82BUTatkMJXN8xvzqsKIx8h3CIE"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
